# This is a basic workflow to help you get started with Actions

name: Build
permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  auto-merge:
    name: "auto-merge"
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: "${{ secrets.PAT }}"
          config: .github/auto-merge.yml
          target: minor

  terraform:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: pack .\terraform\terraform.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: install -source . -force terraform

      - name: Terraform Version
        run: terraform -version
